# EnvironmentVariableList:
#   Global:
#     AZ_IMAGE_NS: azinternal
#     AZ_IMAGE_PROJ: default
#     AZ_CONTAINER_NS: azinternal
#     AZ_CONTAINER_PROJ: default
#   Project:

version: '3'
services:
  minio1:
    image: minio/minio:RELEASE.2019-04-09T01-22-30Z

    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-afs-minio1

    volumes:
      - ../minio_data:/data

    environment:
      MINIO_ACCESS_KEY: minioxxxak
      MINIO_SECRET_KEY: minioxxxsk

    command: server /data

  pg-master:
    image: postgres:9.6

    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-afs-pg-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xxxx1234
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - "../pgdata:/var/lib/postgresql/data/pgdata"

  webserver:
    image: ${AZ_IMAGE_NS:-azinternal}/${AZ_IMAGE_PROJ:-default}/afswebserver
    build:
      context: .

    container_name: ${AZ_CONTAINER_NS:-azinternal}-${AZ_CONTAINER_PROJ:-default}-afs-webserver

    links:
      - "minio1:minio1"
      - "pg-master:postgres"

    depends_on:
      - "minio1"
      - "pg-master"

    environment:
      AFS_SECRETS_FOLDER: "/usr/volumes/share/secrets"

    volumes:
      - ".:/usr/volumes/src/"
      - "../secrets:/usr/volumes/share/secrets"

    command: bash docker-cmd.sh

    # ports:
    #   - "443:443"
    #   - "80:80"
